### ISSUE TITLE
Problem in parameters with Docker-TC

### ISSUE THREAD

**Issue by ValBr11** [lukaszlach/docker-tc#1]
Hello,
I use this work for a project for the University of Klagenfurt in Austria. If I'm coming to you its because I have a problem with it : when I try to change only one parameter, the delay for example, it works but then when I change a second one, the first one is reset. Also when I try to change two parameters in one command, it doesn't works. I send you a screenshot of this, it will be easier to understand I think.
So, I'm asking your help for this, if you have any explications or any ways to solve this.
I remain at your disposal if you need more informations,
Thank you very much.

Valentin Brard

![Screenshot](https://user-images.githubusercontent.com/51376373/58893744-00ca2980-86f1-11e9-94b7-4910246b57e8.png)

**Comment by lukaszlach** [comment]
Fixed in https://github.com/lukaszlach/docker-tc/commit/00dc35f726fd1958105dfdf45006cfa24f1ce42c
