### ISSUE TITLE
How to specify network interface ?

### ISSUE THREAD

**Issue by dceejay** [lukaszlach/docker-tc#11]
If I have a container with multiple internal networks - how do I specify which interface tc will attach itself to ?  the README for the .loss alludes to the capability when it says "...outgoing from the chosen network interface"... so it must be possible - but there is no  com.docker-tc.  parameter for it.

**Comment by quentingodeau** [comment]
Hi @dceejay,
I got the same issue, and didn't see in the code any way to choose an interface. So I made some changes (check the PR) to put traffic control over specific networks, note that if you have multiple interfaces on the same network it will not allow you to choose which interface.
At first I planned to add the capability to specify  the `eth0` or `ethX` interface but they are internal interfaces that docker do not known about. There is external interfaces name but I didn't see any way to know them beforehand.
I hope that it will be enough for your use case :)

**Comment by dceejay** [comment]
sounds workable for me. Thanks
